import { IconBallBaseball, IconCrown, IconGift, IconHeart, IconMicrophone, IconPlayFootball } from "@tabler/icons-react";

// brangay events data for ManageEvents
export const barangayEvents = [
    {
      id: 1,
      title: "Liga ng mga Barangay Basketball Tournament",
      category: "sports",
      description:
        "Annual inter-barangay basketball championship featuring teams from all sitios",
      date: "2024-02-15",
      endDate: "2024-02-25",
      time: "6:00 PM - 10:00 PM",
      venue: "Barangay Basketball Court",
      organizer: "Barangay Sports Committee",
      contact: "Kagawad Pedro Santos",
      phone: "09123456789",
      icon: IconBallBaseball,
      status: "upcoming",
      participants: "16 teams",
      prizes: "₱15,000 Champion, ₱10,000 1st Runner-up, ₱5,000 2nd Runner-up",
      requirements: "Team registration required",
      activities: "Elimination rounds, Semi-finals, Finals",
      categories: "Men's Open Division",
      image: "/images/basketball-tournament.jpg",
      featured: true,
      isActive: true,
      totalRegistrations: 16,
      confirmedRegistrations: 14,
      pendingRegistrations: 2,
      budget: "₱50,000",
      lastUpdated: "2024-01-20T10:30:00Z",
      createdBy: "Admin User",
      createdDate: "2024-01-10T08:00:00Z",
    },
    {
      id: 2,
      title: "Miss Barangay Kaypian 2024",
      category: "pageant",
      description:
        "Annual beauty pageant showcasing the grace and talent of our barangay ladies",
      date: "2024-03-08",
      time: "7:00 PM - 11:00 PM",
      venue: "Barangay Covered Court",
      organizer: "Barangay Women's Committee",
      contact: "Mrs. Maria Garcia",
      phone: "09987654321",
      icon: IconCrown,
      status: "upcoming",
      participants: "12 contestants",
      prizes: "Crown, Sash, ₱10,000 cash prize + prizes from sponsors",
      requirements: "Single, 18-25 years old, Barangay resident",
      activities: "Talent show, Q&A portion, Evening gown competition",
      categories: "Miss Barangay, Miss Congeniality, Best in Talent",
      image: "/images/miss-barangay.jpg",
      featured: true,
      isActive: true,
      totalRegistrations: 12,
      confirmedRegistrations: 10,
      pendingRegistrations: 2,
      budget: "₱75,000",
      lastUpdated: "2024-01-18T14:20:00Z",
      createdBy: "Admin User",
      createdDate: "2024-01-05T09:15:00Z",
    },
    {
      id: 3,
      title: "Pista ng Barangay 2024",
      category: "fiesta",
      description:
        "Grand celebration of our barangay's founding anniversary with cultural shows, food fair, and community activities",
      date: "2024-04-12",
      endDate: "2024-04-14",
      time: "All Day",
      venue: "Barangay Plaza & Streets",
      organizer: "Barangay Council",
      contact: "Barangay Captain Jose Rizal",
      phone: "09111222333",
      icon: IconGift,
      status: "upcoming",
      participants: "Whole community",
      activities: "Cultural shows, Food fair, Games, Fireworks display",
      requirements: "Open to all residents and visitors",
      categories: "Food vendors, Cultural performers, Game booths",
      image: "/images/pista-barangay.jpg",
      featured: true,
      isActive: true,
      totalRegistrations: 45,
      confirmedRegistrations: 38,
      pendingRegistrations: 7,
      budget: "₱200,000",
      lastUpdated: "2024-01-19T11:45:00Z",
      createdBy: "Admin User",
      createdDate: "2024-01-01T10:00:00Z",
    },
    {
      id: 4,
      title: "Volleyball Liga - Women's Division",
      category: "sports",
      description:
        "Inter-sitio women's volleyball tournament promoting sportsmanship and camaraderie",
      date: "2024-02-20",
      endDate: "2024-02-28",
      time: "5:00 PM - 9:00 PM",
      venue: "Barangay Volleyball Court",
      organizer: "SK (Sangguniang Kabataan)",
      contact: "SK Chairman Mark Lopez",
      phone: "09444555666",
      icon: IconPlayFootball,
      status: "upcoming",
      participants: "8 teams",
      prizes: "Trophies and medals for top 3 teams",
      requirements: "Female players, 16-35 years old",
      activities: "Round robin, Semi-finals, Finals",
      categories: "Women's Open Division",
      image: "/images/volleyball.jpg",
      featured: false,
      isActive: true,
      totalRegistrations: 8,
      confirmedRegistrations: 8,
      pendingRegistrations: 0,
      budget: "₱25,000",
      lastUpdated: "2024-01-17T09:15:00Z",
      createdBy: "SK Admin",
      createdDate: "2024-01-08T14:30:00Z",
    },
    {
      id: 5,
      title: "Karaoke Contest - Battle of Voices",
      category: "entertainment",
      description:
        "Singing competition showcasing the musical talents of barangay residents",
      date: "2024-03-15",
      time: "7:00 PM - 11:00 PM",
      venue: "Barangay Hall Function Room",
      organizer: "Barangay Cultural Committee",
      contact: "Mrs. Linda Cruz",
      phone: "09777888999",
      icon: IconMicrophone,
      status: "upcoming",
      participants: "Solo and Duet categories",
      prizes:
        "₱5,000 Grand Champion, ₱3,000 1st Runner-up, ₱2,000 2nd Runner-up",
      requirements: "Registration fee: ₱100",
      activities: "Preliminary rounds, Semi-finals, Grand finals",
      categories: "Solo Male, Solo Female, Duet",
      image: "/images/karaoke-contest.jpg",
      featured: false,
      isActive: true,
      totalRegistrations: 24,
      confirmedRegistrations: 20,
      pendingRegistrations: 4,
      budget: "₱30,000",
      lastUpdated: "2024-01-16T13:30:00Z",
      createdBy: "Admin User",
      createdDate: "2024-01-12T11:20:00Z",
    },
    {
      id: 6,
      title: "Senior Citizens Day Celebration",
      category: "community",
      description:
        "Special celebration honoring our beloved senior citizens with entertainment and fellowship",
      date: "2024-04-20",
      time: "9:00 AM - 4:00 PM",
      venue: "Barangay Hall",
      organizer: "Senior Citizens Association",
      contact: "Mrs. Carmen Torres",
      phone: "09888999000",
      icon: IconHeart,
      status: "upcoming",
      participants: "All senior citizens (60+ years old)",
      activities:
        "Free health check-up, Entertainment, Free lunch, Games with prizes",
      requirements: "Senior Citizen ID",
      categories: "Health services, Entertainment, Games",
      image: "/images/senior-citizens.jpg",
      featured: false,
      isActive: true,
      totalRegistrations: 67,
      confirmedRegistrations: 67,
      pendingRegistrations: 0,
      budget: "₱45,000",
      lastUpdated: "2024-01-15T16:45:00Z",
      createdBy: "Admin User",
      createdDate: "2024-01-03T08:30:00Z",
    },
  ];

  // data registration for ManageEvents
export const eventRegistrations = [
    {
      id: 1,
      registrationNumber: "ER-2024-001",
      residentName: "Team Sitio 1 Warriors",
      residentEmail: "team.warriors@email.com",
      residentPhone: "09123456789",
      residentAddress: "Sitio 1, Barangay Kaypian, San Jose Del Monte, Bulacan",
      eventTitle: "Liga ng mga Barangay Basketball Tournament",
      eventCategory: "sports",
      eventDate: "2024-02-15",
      registrationDate: "2024-01-15T10:30:00Z",
      status: "confirmed",
      paymentStatus: "paid",
      registrationFee: "₱500",
      teamMembers: "12 players",
      notes: "Complete team roster submitted. Payment confirmed.",
      processedBy: "Admin User",
      processedDate: "2024-01-15T11:00:00Z",
      specialRequirements: "Team uniform in barangay colors",
      contactNumber: "09123456789",
    },
    {
      id: 2,
      registrationNumber: "ER-2024-002",
      residentName: "Maria Santos",
      residentEmail: "maria.santos@email.com",
      residentPhone: "09876543210",
      residentAddress:
        "456 Oak Ave, Barangay Kaypian, San Jose Del Monte, Bulacan",
      eventTitle: "Miss Barangay Kaypian 2024",
      eventCategory: "pageant",
      eventDate: "2024-03-08",
      registrationDate: "2024-01-20T14:15:00Z",
      status: "pending_approval",
      paymentStatus: "pending",
      registrationFee: "₱1,000",
      teamMembers: "1 contestant",
      notes: "Documents submitted for verification",
      processedBy: null,
      processedDate: null,
      specialRequirements: "Age verification, talent performance",
      contactNumber: "09876543210",
    },
    {
      id: 3,
      registrationNumber: "ER-2024-003",
      residentName: "Aling Rosa's Kakanin",
      residentEmail: "rosa.kakanin@email.com",
      residentPhone: "09192837465",
      residentAddress:
        "789 Pine St, Barangay Kaypian, San Jose Del Monte, Bulacan",
      eventTitle: "Pista ng Barangay 2024",
      eventCategory: "fiesta",
      eventDate: "2024-04-12",
      registrationDate: "2024-01-22T09:45:00Z",
      status: "confirmed",
      paymentStatus: "paid",
      registrationFee: "₱2,000",
      teamMembers: "Food vendor booth",
      notes: "Food vendor permit approved. Health certificate submitted.",
      processedBy: "Admin User",
      processedDate: "2024-01-22T10:30:00Z",
      specialRequirements: "Food safety permit, health certificate",
      contactNumber: "09192837465",
    },
    {
      id: 4,
      registrationNumber: "ER-2024-004",
      residentName: "Juan Dela Cruz",
      residentEmail: "juan.delacruz@email.com",
      residentPhone: "09345678901",
      residentAddress:
        "321 Elm St, Barangay Kaypian, San Jose Del Monte, Bulacan",
      eventTitle: "Karaoke Contest - Battle of Voices",
      eventCategory: "entertainment",
      eventDate: "2024-03-15",
      registrationDate: "2024-01-25T16:20:00Z",
      status: "cancelled",
      paymentStatus: "refunded",
      registrationFee: "₱100",
      teamMembers: "1 solo performer",
      notes: "Registration cancelled due to personal reasons. Fee refunded.",
      processedBy: "Admin User",
      processedDate: "2024-01-26T09:00:00Z",
      specialRequirements: "Song selection, backing track",
      contactNumber: "09345678901",
    },
  ];