import { IconArmchair2, IconBuildingWarehouse, IconSpeakerphone, IconTable, IconTent, IconTools } from "@tabler/icons-react";

  // item inventory in ManageItems
export const itemsInventory = [
    {
      id: 1,
      name: "Plastic Chairs",
      category: "furniture",
      description: "White plastic chairs perfect for events and gatherings",
      available: 85,
      total: 100,
      borrowed: 15,
      icon: IconArmchair2,
      condition: "Good",
      borrowingFee: "Free",
      maxBorrowDays: 7,
      deliveryAvailable: true,
      requirements: ["Valid ID", "Barangay Residency Proof"],
      notes: "Available quantity updates the day after borrow date",
      isActive: true,
      totalBookings: 245,
      activeBookings: 15,
      overdueBookings: 2,
      lastUpdated: "2024-01-20T10:30:00Z",
      addedBy: "Admin User",
      addedDate: "2023-06-15T08:00:00Z",
    },
    {
      id: 2,
      name: "Folding Tables",
      category: "furniture",
      description: "6ft folding tables for events and meetings",
      available: 25,
      total: 30,
      borrowed: 5,
      icon: IconTable,
      condition: "Excellent",
      borrowingFee: "Free",
      maxBorrowDays: 7,
      deliveryAvailable: true,
      requirements: ["Valid ID", "Barangay Residency Proof"],
      notes: "Available quantity updates the day after borrow date",
      isActive: true,
      totalBookings: 156,
      activeBookings: 5,
      overdueBookings: 0,
      lastUpdated: "2024-01-19T14:15:00Z",
      addedBy: "Admin User",
      addedDate: "2023-06-15T08:00:00Z",
    },
    {
      id: 3,
      name: "Sound System",
      category: "electronics",
      description: "Portable sound system with wireless microphones",
      available: 2,
      total: 3,
      borrowed: 1,
      icon: IconSpeakerphone,
      condition: "Good",
      borrowingFee: "₱200/day",
      maxBorrowDays: 3,
      deliveryAvailable: true,
      requirements: [
        "Valid ID",
        "Security Deposit: ₱2,000 (cash)",
        "Technical Briefing Required",
      ],
      notes:
        "Payment and deposit at barangay office. Technical briefing mandatory.",
      isActive: true,
      totalBookings: 89,
      activeBookings: 1,
      overdueBookings: 1,
      lastUpdated: "2024-01-18T16:45:00Z",
      addedBy: "Admin User",
      addedDate: "2023-07-10T09:30:00Z",
    },
    {
      id: 4,
      name: "Event Tents",
      category: "shelter",
      description: "Large white tents for outdoor events (10x10 ft)",
      available: 6,
      total: 8,
      borrowed: 2,
      icon: IconTent,
      condition: "Good",
      borrowingFee: "₱100/day",
      maxBorrowDays: 5,
      deliveryAvailable: true,
      requirements: ["Valid ID", "Event Permit", "Setup Location Details"],
      notes:
        "Payment at barangay office. Setup assistance available for delivery.",
      isActive: true,
      totalBookings: 67,
      activeBookings: 2,
      overdueBookings: 0,
      lastUpdated: "2024-01-17T11:20:00Z",
      addedBy: "Admin User",
      addedDate: "2023-08-05T10:15:00Z",
    },
    {
      id: 5,
      name: "Cleaning Tools Set",
      category: "tools",
      description: "Complete set: brooms, mops, and cleaning supplies",
      available: 18,
      total: 20,
      borrowed: 2,
      icon: IconTools,
      condition: "Fair",
      borrowingFee: "Free",
      maxBorrowDays: 3,
      deliveryAvailable: false,
      requirements: ["Valid ID"],
      notes: "Walk-in pickup only at barangay office",
      isActive: true,
      totalBookings: 134,
      activeBookings: 2,
      overdueBookings: 0,
      lastUpdated: "2024-01-16T09:10:00Z",
      addedBy: "Admin User",
      addedDate: "2023-06-20T14:30:00Z",
    },
    {
      id: 6,
      name: "Projector & Screen",
      category: "electronics",
      description: "HD projector with portable projection screen",
      available: 1,
      total: 2,
      borrowed: 1,
      icon: IconBuildingWarehouse,
      condition: "Excellent",
      borrowingFee: "₱300/day",
      maxBorrowDays: 3,
      deliveryAvailable: true,
      requirements: [
        "Valid ID",
        "Security Deposit: ₱5,000 (cash)",
        "Technical Training Certificate",
      ],
      notes:
        "Payment and deposit at barangay office. Technical training required.",
      isActive: true,
      totalBookings: 45,
      activeBookings: 1,
      overdueBookings: 0,
      lastUpdated: "2024-01-15T13:25:00Z",
      addedBy: "Admin User",
      addedDate: "2023-09-12T11:45:00Z",
    },
  ];

  // item bookings in ManageItems
export const itemBookings = [
    {
      id: 1,
      bookingNumber: "BK-2024-001",
      residentName: "Juan Dela Cruz",
      residentEmail: "juan.delacruz@email.com",
      residentPhone: "09123456789",
      residentAddress:
        "123 Main St, Barangay Kaypian, San Jose Del Monte, Bulacan",
      itemName: "Plastic Chairs",
      itemCategory: "furniture",
      quantity: 50,
      borrowDate: "2024-01-20",
      returnDate: "2024-01-22",
      actualReturnDate: null,
      purpose: "Family Birthday Party",
      eventLocation: "123 Main St, Kaypian",
      status: "active",
      daysLeft: 2,
      bookingDate: "2024-01-18T08:30:00Z",
      deliveryMethod: "delivery",
      deliveryStatus: "delivered",
      paymentStatus: "paid",
      totalAmount: "Free",
      processedBy: "Admin User",
      processedDate: "2024-01-18T10:15:00Z",
      notes: "Delivered successfully. Items in good condition.",
      isSenior: false,
      isPregnant: false,
      contactNumber: "09123456789",
    },
    {
      id: 2,
      bookingNumber: "BK-2024-002",
      residentName: "Maria Santos",
      residentEmail: "maria.santos@email.com",
      residentPhone: "09876543210",
      residentAddress:
        "456 Oak Ave, Barangay Kaypian, San Jose Del Monte, Bulacan",
      itemName: "Sound System",
      itemCategory: "electronics",
      quantity: 1,
      borrowDate: "2024-01-15",
      returnDate: "2024-01-18",
      actualReturnDate: null,
      purpose: "Wedding Reception",
      eventLocation: "456 Oak Ave, Kaypian",
      status: "overdue",
      daysLeft: -3,
      bookingDate: "2024-01-12T14:20:00Z",
      deliveryMethod: "pickup",
      deliveryStatus: "picked_up",
      paymentStatus: "paid",
      totalAmount: "₱600 + ₱2,000 deposit",
      processedBy: "Admin User",
      processedDate: "2024-01-12T16:30:00Z",
      notes: "Extended event duration. Resident contacted for return.",
      isSenior: false,
      isPregnant: false,
      contactNumber: "09876543210",
    },
    {
      id: 3,
      bookingNumber: "BK-2024-003",
      residentName: "Pedro Reyes",
      residentEmail: "pedro.reyes@email.com",
      residentPhone: "09192837465",
      residentAddress:
        "789 Pine St, Barangay Kaypian, San Jose Del Monte, Bulacan",
      itemName: "Folding Tables",
      itemCategory: "furniture",
      quantity: 10,
      borrowDate: "2024-01-25",
      returnDate: "2024-01-27",
      actualReturnDate: null,
      purpose: "Community Meeting",
      eventLocation: "Barangay Hall",
      status: "pending_approval",
      daysLeft: 5,
      bookingDate: "2024-01-20T11:45:00Z",
      deliveryMethod: "pickup",
      deliveryStatus: "pending",
      paymentStatus: "pending",
      totalAmount: "Free",
      processedBy: null,
      processedDate: null,
      notes: "",
      isSenior: true,
      isPregnant: false,
      contactNumber: "09192837465",
    },
    {
      id: 4,
      bookingNumber: "BK-2024-004",
      residentName: "Ana Garcia",
      residentEmail: "ana.garcia@email.com",
      residentPhone: "09345678901",
      residentAddress:
        "321 Elm St, Barangay Kaypian, San Jose Del Monte, Bulacan",
      itemName: "Event Tents",
      itemCategory: "shelter",
      quantity: 2,
      borrowDate: "2024-01-22",
      returnDate: "2024-01-25",
      actualReturnDate: null,
      purpose: "Graduation Party",
      eventLocation: "321 Elm St, Kaypian",
      status: "confirmed",
      daysLeft: 3,
      bookingDate: "2024-01-19T09:15:00Z",
      deliveryMethod: "delivery",
      deliveryStatus: "scheduled",
      paymentStatus: "paid",
      totalAmount: "₱300",
      processedBy: "Admin User",
      processedDate: "2024-01-19T10:30:00Z",
      notes:
        "Delivery scheduled for Jan 22, 8:00 AM. Setup assistance included.",
      isSenior: false,
      isPregnant: true,
      contactNumber: "09345678901",
    },
  ];