// service data for ManageServices
export const mockServices = [
  {
    id: 1,
    name: "Free Medical Check-up",
    category: "health",
    description: "General health examination by barangay health workers",
    schedule: "Every Monday & Wednesday",
    time: "8:00 AM - 12:00 PM",
    location: "Barangay Health Center",
    cost: "FREE",
    requirements: ["Valid ID", "Barangay Residency"],
    serviceType: "walk-in",
    available: true,
    slots: "15 slots available",
    contact: "Nurse Maria Santos",
    phone: "(02) 123-4567",
    details: "Basic health screening including blood pressure, weight, height measurements, and general consultation.",
    isActive: true,
    totalAppointments: 156,
    activeAppointments: 12,
    completedThisMonth: 45,
    lastUpdated: "2024-01-20T10:30:00Z",
    addedBy: "Admin User",
    addedDate: "2023-06-15T08:00:00Z",
  },
  {
    id: 2,
    name: "Anti-Rabies Vaccination",
    category: "veterinary",
    description: "Free vaccination for dogs and cats",
    schedule: "Every 2nd Saturday",
    time: "9:00 AM - 3:00 PM",
    location: "Barangay Covered Court",
    cost: "FREE",
    requirements: ["Pet ownership proof", "Previous vaccination record (if any)"],
    serviceType: "walk-in",
    available: true,
    slots: "50 pets can be accommodated",
    contact: "Dr. Juan Dela Cruz (City Vet)",
    phone: "(02) 234-5678",
    details: "Annual anti-rabies vaccination program. Bring your pets early as slots are limited.",
    isActive: true,
    totalAppointments: 89,
    activeAppointments: 0,
    completedThisMonth: 23,
    lastUpdated: "2024-01-18T14:20:00Z",
    addedBy: "Admin User",
    addedDate: "2023-06-20T09:15:00Z",
  },
  {
    id: 3,
    name: "Senior Citizen Health Check",
    category: "health",
    description: "Specialized health services for senior citizens",
    schedule: "Every Friday",
    time: "8:00 AM - 11:00 AM",
    location: "Barangay Health Center",
    cost: "FREE",
    requirements: ["Senior Citizen ID", "Barangay Residency"],
    serviceType: "priority",
    available: true,
    slots: "20 slots available",
    contact: "Nurse Elena Rodriguez",
    phone: "(02) 345-6789",
    details: "Priority health services including blood pressure monitoring, diabetes screening, and medication consultation.",
    isActive: true,
    totalAppointments: 234,
    activeAppointments: 8,
    completedThisMonth: 67,
    lastUpdated: "2024-01-19T11:45:00Z",
    addedBy: "Admin User",
    addedDate: "2023-07-01T10:30:00Z",
  },
  {
    id: 4,
    name: "Legal Assistance & Consultation",
    category: "legal",
    description: "Free legal advice and document preparation",
    schedule: "Every Tuesday & Thursday",
    time: "1:00 PM - 5:00 PM",
    location: "Barangay Hall - Conference Room",
    cost: "FREE",
    requirements: ["Valid ID", "Relevant documents"],
    serviceType: "appointment",
    available: true,
    slots: "10 appointments per day",
    contact: "Atty. Ricardo Morales",
    phone: "(02) 456-7890",
    details: "Legal consultation for family matters, labor disputes, and document preparation assistance.",
    isActive: true,
    totalAppointments: 78,
    activeAppointments: 15,
    completedThisMonth: 32,
    lastUpdated: "2024-01-17T09:15:00Z",
    addedBy: "Admin User",
    addedDate: "2023-08-15T14:20:00Z",
  },
  {
    id: 5,
    name: "Maternal & Child Health",
    category: "health",
    description: "Pre-natal and post-natal care for mothers",
    schedule: "Every Monday, Wednesday, Friday",
    time: "8:00 AM - 12:00 PM",
    location: "Barangay Health Center",
    cost: "FREE",
    requirements: ["Pregnancy record", "Valid ID"],
    serviceType: "walk-in",
    available: true,
    slots: "12 slots available",
    contact: "Midwife Carmen Villanueva",
    phone: "(02) 567-8901",
    details: "Complete maternal care including check-ups, vitamins distribution, and health education.",
    isActive: true,
    totalAppointments: 145,
    activeAppointments: 18,
    completedThisMonth: 56,
    lastUpdated: "2024-01-16T13:30:00Z",
    addedBy: "Admin User",
    addedDate: "2023-06-25T11:00:00Z",
  },
  {
    id: 6,
    name: "Emergency Ambulance Service",
    category: "emergency",
    description: "24/7 emergency transport to nearest hospital",
    schedule: "24/7 Available",
    time: "Anytime",
    location: "Mobile Service",
    cost: "₱500 - ₱1,000 (depending on distance)",
    requirements: ["Emergency situation", "Contact person"],
    serviceType: "emergency",
    available: true,
    slots: "1 ambulance available",
    contact: "Emergency Hotline",
    phone: "911 or (02) 901-2345",
    details: "Emergency transport service. Payment can be made after service or through installment.",
    isActive: true,
    totalAppointments: 34,
    activeAppointments: 2,
    completedThisMonth: 8,
    lastUpdated: "2024-01-15T16:45:00Z",
    addedBy: "Admin User",
    addedDate: "2023-05-10T08:30:00Z",
  }
];

 // service appointments for ManageServices
export const mockServiceAppointments = [
  {
    id: 1,
    appointmentNumber: "SA-2024-001",
    residentName: "Maria Santos",
    residentEmail: "maria.santos@email.com",
    residentPhone: "09123456789",
    residentAddress: "123 Main St, Barangay Kaypian, San Jose Del Monte, Bulacan",
    serviceName: "Free Medical Check-up",
    serviceCategory: "health",
    appointmentDate: "2024-01-22",
    appointmentTime: "9:00 AM",
    requestDate: "2024-01-20T14:30:00Z",
    status: "confirmed",
    notes: "Regular check-up for hypertension monitoring",
    processedBy: "Admin User",
    processedDate: "2024-01-20T15:00:00Z",
    isSenior: false,
    isPregnant: false,
    specialRequirements: "",
    contactNumber: "09123456789",
  },
  {
    id: 2,
    appointmentNumber: "SA-2024-002",
    residentName: "Pedro Reyes",
    residentEmail: "pedro.reyes@email.com",
    residentPhone: "09876543210",
    residentAddress: "456 Oak Ave, Barangay Kaypian, San Jose Del Monte, Bulacan",
    serviceName: "Legal Assistance & Consultation",
    serviceCategory: "legal",
    appointmentDate: "2024-01-23",
    appointmentTime: "2:00 PM",
    requestDate: "2024-01-18T11:15:00Z",
    status: "pending_approval",
    notes: "Need legal advice for property dispute with neighbor",
    processedBy: null,
    processedDate: null,
    isSenior: true,
    isPregnant: false,
    specialRequirements: "Senior citizen - priority scheduling",
    contactNumber: "09876543210",
  },
  {
    id: 3,
    appointmentNumber: "SA-2024-003",
    residentName: "Ana Garcia",
    residentEmail: "ana.garcia@email.com",
    residentPhone: "09192837465",
    residentAddress: "789 Pine St, Barangay Kaypian, San Jose Del Monte, Bulacan",
    serviceName: "Maternal & Child Health",
    serviceCategory: "health",
    appointmentDate: "2024-01-21",
    appointmentTime: "10:00 AM",
    requestDate: "2024-01-19T09:45:00Z",
    status: "completed",
    notes: "Pre-natal check-up completed. Next appointment scheduled for Feb 5.",
    processedBy: "Admin User",
    processedDate: "2024-01-19T10:15:00Z",
    isSenior: false,
    isPregnant: true,
    specialRequirements: "Pregnant - priority care needed",
    contactNumber: "09192837465",
  },
  {
    id: 4,
    appointmentNumber: "SA-2024-004",
    residentName: "Juan Dela Cruz",
    residentEmail: "juan.delacruz@email.com",
    residentPhone: "09345678901",
    residentAddress: "321 Elm St, Barangay Kaypian, San Jose Del Monte, Bulacan",
    serviceName: "Senior Citizen Health Check",
    serviceCategory: "health",
    appointmentDate: "2024-01-19",
    appointmentTime: "8:30 AM",
    requestDate: "2024-01-17T16:20:00Z",
    status: "no_show",
    notes: "Resident did not show up for appointment. Rescheduling needed.",
    processedBy: "Admin User",
    processedDate: "2024-01-17T17:00:00Z",
    isSenior: true,
    isPregnant: false,
    specialRequirements: "Senior citizen with mobility issues",
    contactNumber: "09345678901",
  }
];